name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test-dotnet:
    name: Test .NET
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run dotnet tests
        run: dotnet test
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test --verbosity normal
  test-front-end:
    name: Test front-end
    runs-on: ubuntu-latest
    env:
      working-directory: ./AttunedWeb/front-end
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install
        working-directory: ${{env.working-directory}}
        run: npm install
      - name: Lint
        working-directory: ${{env.working-directory}}
        run: npm run lint
      - name: Test
        working-directory: ${{env.working-directory}}
        run: npm run test-compile

